**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [ ]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [ ]:
import numpy as np

# Create a zero vector of size 10
vector = np.zeros(10)

# Set the fifth value (index 4) to 1
vector[4] = 1

print(vector)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [ ]:
#Code here
import random
a=int(input("a"))
b=int(input("b"))
z= np.random.random((a,b)).mean()
z

a4
b1


0.3971429329516436

###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [ ]:
def create( a ,  b):
  x=np.zeros((a,b))
  # print(x)
  x[:,::b-1]=1
  x[::a-1,:]=1
  print(x)
a=int(input("a: "))
b=int(input("b: "))
create(a,b)

a: 7
b: 8
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [ ]:
#Code here
import numpy as np

# Create a vector of size 10 with values ranging from 0 to 1, excluding both
vector = np.linspace(0, 1, 12)[1:-1]

print(vector)


[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:
#Code here

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [ ]:
#Code here
np.tile(np.arange(5),(5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [ ]:
a=np.random.randint(1,100, size=(10,2))
point = np.array([2,3])
distance= ((a[:,0]-point[0])**2+(a[:,1]-point[1])**2)**0.5
distance.astype('int')

array([107,  76,  88,  96,  98,  11,  73, 103,  92,  57])

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
#Code here
1,5,4

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [ ]:
#Code here
s='1 2 3 4 -8 -10'
s=s.split()
p=np.array(s)
p[::-1].astype('float')

array([-10.,  -8.,   4.,   3.,   2.,   1.])

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [ ]:
np.size(np.array([[1, 2],[3,4]]))

4

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [ ]:
#Code here
def softmax(l):
  if len(l.shape)==1:
    f=np.exp(l)/np.sum(np.exp(l))
    return f
  else:
    raise AttributeError

a=np.array([86.03331084 ,37.7285648,  48.64908087, 87.16563062, 38.40852563, 37.20006318])
softmax(a)

array([2.43733248e-01, 2.56112114e-22, 1.41628283e-17, 7.56266752e-01,
       5.05514197e-22, 1.50974911e-22])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [ ]:
#Coder here
def stack(*args):
  f=0
  for i in args:
    if isinstance(i,np.ndarray):
        if f:
          a=np.vstack((a,i))
        else:
          f=1
          a=np.array(i)
    else:
      raise TypeError(" accepts the numpy array")

  return a
a= np.array([[0, 1, 2, 3, 4],
    [5, 6, 7, 8, 9]])

b= np.array([[1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1]])

stack(a,b)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [ ]:
#Code here
def date_array(start  , end  ):
  if not isinstance(start_date, str) or not isinstance(end_date, str):
        raise ValueError("Both arguments must be strings")
  a=np.array([start])
  while(1):
    p = a[-1].split('-')
    yr, mn, day=p[0],int(p[1]),int(p[2])
    day+=1
    new_date= yr+'-'+str(mn+1)+'-'+str(1).zfill(2) if day>30 else  yr+'-'+str(mn)+'-'+str(day).zfill(2)
    a=np.append(a,new_date)
    if new_date==end:
      break
  return a

date_array(start = '2022-12-01', end = '2022-12-06')

array(['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04',
       '2022-12-05', '2022-12-06'], dtype='<U10')

###`Q-14:` Subtract the mean of each row from a matrix.

In [ ]:
#code here
p=np.random.randint(1,5,(15)).reshape(3,5)
print(p)
p-np.mean(p,axis=0)

[[4 4 3 2 4]
 [2 1 4 2 4]
 [4 3 1 3 2]]


array([[ 0.66666667,  1.33333333,  0.33333333, -0.33333333,  0.66666667],
       [-1.33333333, -1.66666667,  1.33333333, -0.33333333,  0.66666667],
       [ 0.66666667,  0.33333333, -1.66666667,  0.66666667, -1.33333333]])

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [ ]:
#Code here
p=np.random.randint(1,5,(15)).reshape(3,5)
print(p)
p[:,[0,1]]=p[:,[1,0]]
p

[[2 3 4 2 3]
 [3 3 2 2 2]
 [2 3 4 1 1]]


array([[3, 2, 4, 2, 3],
       [3, 3, 2, 2, 2],
       [3, 2, 4, 1, 1]])

###`Q-16:` Replace odd elements in arrays with -1.

In [ ]:
#Code here

In [ ]:
p=np.random.randint(1,5,(15)).reshape(3,5)
print(p)
p[p%2==1]=-1
p

[[3 2 1 1 3]
 [1 4 2 3 4]
 [1 2 4 2 4]]


array([[-1,  2, -1, -1, -1],
       [-1,  4,  2, -1,  4],
       [-1,  2,  4,  2,  4]])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [ ]:
#Code here
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
c= np.vstack((a,b))
c.max(axis=0)

array([6, 3, 1, 7, 8])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [2]:
# Given
import numpy as np
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[ 485, 8616, 7972, 5421, 1249],
       [ 959, 1703, 1280, 4018, 8789],
       [1570, 6243, 3877, 4478, 3312],
       [6168, 1183, 3006, 1112, 9754],
       [8192, 3748, 4143, 2251, 7202],
       [5520, 6845,  461,   26, 4890],
       [2239, 5844, 6176, 2856,  371],
       [6299, 7109, 6048, 4510, 8209]])

In [4]:
#Code here
arr1=(arr1-np.min(arr1))/ (np.max(arr1)-np.min(arr1))
arr1

array([[0.04718339, 0.88301809, 0.81681743, 0.5545847 , 0.12571957],
       [0.09590872, 0.17238898, 0.12890625, 0.41036184, 0.90080181],
       [0.15871711, 0.63908306, 0.3958676 , 0.45764803, 0.33778783],
       [0.63137336, 0.11893503, 0.30633224, 0.11163651, 1.        ],
       [0.83943257, 0.38260691, 0.42321135, 0.22872122, 0.73766447],
       [0.56476151, 0.70096628, 0.04471628, 0.        , 0.5       ],
       [0.22748766, 0.59806743, 0.63219572, 0.29091283, 0.03546464],
       [0.64483964, 0.72810444, 0.61903783, 0.4609375 , 0.8411801 ]])

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [12]:
#Code here
def cal(array, n):
  if (len(array)<n):
    raise ValueError("Value of n is should be than length of array")
  elif array.ndim>1:
    raise ValueError("Give 1-D array please")
  else:
    return np.sort(array)[-n]

arr1= np.array([12,34,40,7,1,0])
cal(arr1,1)

40

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [16]:
#code here
a = np.array([1,2,3])
repeat = np.repeat(a,3)
tile= np.tile(a,3)
np.concatenate((repeat, tile))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])